export const TRANSLATIONS = {
    "es-ES": {
      "triviaTitle": "ENCUESTA IA ARCADE",
      "triviaSubtitle": "¡PRESS START PARA INICIAR!",
      "registerTitle": "CREACION DE PERSONAJE",
      "surveyTitle": "MISION: CONOCIMIENTO",
      "nameLabel": "NOMBRE / NICKNAME",
      "institutionLabel": "INSTITUCION / ORGANIZACION",
      "experienceLabel": "EXPERIENCIA EN DIVULGACION",
      "selectAvatarLabel": "ELIGE TU AVATAR",
      "woman": "Mujer",
      "man": "Hombre",
      "robot": "Robot",
      "ai": "IA",
      "nextButton": "SIGUIENTE NIVEL >>",
      "finishButton": "FINALIZAR MISION",
      "insertCoinText": "INSERT COIN / START",
      "fillAllFieldsAlert": "ERROR: DATOS INCOMPLETOS",
      "q1": "¿Con qué frecuencia utilizas herramientas de IA?",
      "q1a": "Diariamente",
      "q1b": "Semanalmente",
      "q1c": "Mensualmente",
      "q1d": "Nunca o casi nunca",
      "q2": "¿Cuál es tu nivel de conocimiento sobre IA?",
      "q2a": "Experto - Entiendo cómo funciona",
      "q2b": "Intermedio - La uso regularmente",
      "q2c": "Básico - La he probado pocas veces",
      "q2d": "Ninguno - Estoy comenzando",
      "q3": "¿Has usado IA para divulgación científica?",
      "q3a": "Sí, frecuentemente",
      "q3b": "Sí, ocasionalmente",
      "q3c": "No, pero me interesa",
      "q3d": "No, no lo había considerado",
      "q4": "¿Pagas por algún servicio premium de IA?",
      "q4a": "Sí, ChatGPT Plus/Pro",
      "q4b": "Sí, Claude Pro",
      "q4c": "Sí, otro servicio",
      "q4d": "No, solo uso versiones gratuitas",
      "q5": "¿Cuál es tu opinión sobre IA en divulgación científica?",
      "q5a": "Muy positiva - Es transformadora",
      "q5b": "Positiva - Útil con precauciones",
      "q5c": "Neutral - Requiere más evaluación",
      "q5d": "Preocupada - Tiene riesgos",
      "q6": "¿Qué herramientas de IA has usado? (selecciona principal)",
      "q6a": "ChatGPT",
      "q6b": "Claude",
      "q6c": "Gemini/Bard",
      "q6d": "Otra o ninguna",
      "q7": "¿Cuál es tu principal preocupación sobre el uso de IA?",
      "q7a": "Desinformación y alucinaciones",
      "q7b": "Privacidad y datos",
      "q7c": "Reemplazo de empleos",
      "q7d": "No tengo preocupaciones importantes",
      "thanksTitle": "¡MISION CUMPLIDA!",
      "resultsSubtitle": "SCORE: 100% COMPLETADO",
      "yourAnswers": "REGISTRO DE MISION:",
      "printButton": "DESCARGAR REPORTE",
      "playAgainButton": "REINICIAR JUEGO"
    }
  };
  
  export const t = (key: keyof typeof TRANSLATIONS["es-ES"]) => TRANSLATIONS['es-ES'][key] || key;
  
  export const SURVEY_QUESTIONS = [
    { id: 'q1', question: t('q1'), options: [t('q1a'), t('q1b'), t('q1c'), t('q1d')] },
    { id: 'q2', question: t('q2'), options: [t('q2a'), t('q2b'), t('q2c'), t('q2d')] },
    { id: 'q3', question: t('q3'), options: [t('q3a'), t('q3b'), t('q3c'), t('q3d')] },
    { id: 'q4', question: t('q4'), options: [t('q4a'), t('q4b'), t('q4c'), t('q4d')] },
    { id: 'q5', question: t('q5'), options: [t('q5a'), t('q5b'), t('q5c'), t('q5d')] },
    { id: 'q6', question: t('q6'), options: [t('q6a'), t('q6b'), t('q6c'), t('q6d')] },
    { id: 'q7', question: t('q7'), options: [t('q7a'), t('q7b'), t('q7c'), t('q7d')] }
  ];